name: find_anime
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # routes
  beamer: ^1.5.0
  url_strategy: ^0.2.0
  #
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.1.0
  equatable: ^2.0.3
  # other packages
  http: ^0.13.4
  duration: ^3.0.11
  url_launcher: ^6.1.5
  file_picker: ^5.0.0
  json_annotation: ^4.6.0
  video_player: ^2.4.5
  breakpoint: ^1.2.0
  colorize_text_avatar: ^1.0.2
  waterfall_flow: ^3.0.2
  intl: ^0.17.0
  flutter_dropzone: ^3.0.5
  pasteboard: ^0.2.0
  mime: ^1.0.2

  tracemoe_repository:
    path: packages/tracemoe_repository
  tracemoe_api:
    path: packages/tracemoe_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  flutter_lints: ^2.0.1
  bloc_test: ^9.0.3
  dart_code_metrics: ^4.17.0
  json_serializable: ^6.3.1
  build_web_compilers: ^3.2.4
  mocktail: ^0.3.0
  coverage: ^1.5.0


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

flutter_intl:
  enabled: true
