name: find_anime
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # routes
  beamer: ^1.5.0
  url_strategy: ^0.2.0
  #
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  freezed_annotation: ^2.1.0
  equatable: ^2.0.3
  # other packages
  http: ^0.13.4
  duration: ^3.0.11
  url_launcher: ^6.1.5
  file_picker: ^8.0.3
  json_annotation: ^4.6.0
  video_player: ^2.4.5
  breakpoint: ^1.2.0
  colorize_text_avatar: ^1.0.2
  waterfall_flow: ^3.0.2
  intl: ^0.18.1
  flutter_dropzone: ^4.0.0
  pasteboard: ^0.2.0
  mime: ^1.0.2

  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4

  tracemoe_repository:
    path: packages/tracemoe_repository
  tracemoe_api:
    path: packages/tracemoe_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  flutter_lints: ^3.0.2
  bloc_test: ^9.0.3
  dart_code_metrics: ^5.7.6
  json_serializable: ^6.3.1
  build_web_compilers: ^4.0.10
  mocktail: ^1.0.3
  coverage: ^1.5.0




# The following section is specific to Flutter.
flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  arb_dir: lib/src/core/l10n
  output_dir: lib/src/core/generated/localization

flutter_gen:
  output: lib/src/core/generated/resources